name: Famashi
description: Medicine Taking Reminder Application

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter_local_notifications: ^6.0.0
  image_picker: ^0.7.5
  intl: ^0.17.0
  lottie: ^1.0.1
  niku: ^1.0.6
  package_info: ^2.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  timezone: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animation/FamashiLogo.json
    - assets/logo/logo-short-01.png
    - assets/logo/logo-short-02.png
    - assets/logo/logo-short-03.png
    - assets/logo/logo-long-01.png
    - assets/logo/logo-long-02.png
    - assets/logo/logo-long-03.png
    - assets/images/authenticate-bg.png
    - assets/images/medicine-default.png
    - assets/images/no-medicine.png
    - assets/images/no-allergy.png
    - assets/images/no-history.png
    - assets/images/no-notification.png

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-VariableFont_wght.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Iconly
      fonts:
        - asset: assets/fonts/Iconly-light.ttf
    - family: CoolIcons
      fonts:
        - asset: assets/fonts/Coolicons.ttf
